name: DVC - AWS S3 bucket Workflow
on:
  workflow_dispatch:

jobs:
  dvc-aws-s3-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python Packages
        run: |
          pip install -r requirements.txt
          pip install pyopenssl --upgrade  # to handle error (https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check)


      - name: DVC Pull Data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          dvc pull -r myremote -v
